
INSERT INTO ROLES (ID,NAME) VALUES (1,'User');
INSERT INTO ROLES (ID,NAME) VALUES (2,'Admin');
INSERT INTO ROLES (ID,NAME) VALUES (3,'User_Admin');

INSERT INTO PERSON (ID,USERNAME, PASSWORD)VALUES (1,'user', 'test');
INSERT INTO PERSON (ID,USERNAME, PASSWORD) VALUES (2,'admin', 'test');
INSERT INTO PERSON (ID,USERNAME, PASSWORD) VALUES (3,'user_admin', 'test');
